spring:
  dubbo:
    application:
      name: red-consumer
    registry:
      protocol: zookeeper
      address: 192.168.27.153:2181
    protocol:
      name: dubbo
      port: 20880
      host: localhost
    scan: com.zls.consumer
server:
  port: 8080
# slf4j日志配置
logging:
  # 配置级别
  #分包配置级别，即不同的目录下可以使用不同的级别
  level:
    com: debug
  # 在不指定路径，只指定输出日志的文件名，默认输出至当前项目下
  # 若指定，则会输出至指定目录下
  file:
    name: log\redpacket.log